-- DROP SCHEMA public;


-- DROP SEQUENCE public.post_seq;

CREATE SEQUENCE public.post_seq
	INCREMENT BY 50
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.question_seq;

CREATE SEQUENCE public.question_seq
	INCREMENT BY 50
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.users_id_seq;

CREATE SEQUENCE public.users_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	bio text NULL,
	created_at varchar(255) NULL,
	email varchar(255) NULL,
	"password" varchar(255) NULL,
	photo_url varchar(255) NULL,
	"role" varchar(255) NULL,
	username varchar(255) NULL,
	CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username),
	CONSTRAINT users_id_not_null NOT NULL id,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);


-- public.post definition

-- Drop table

-- DROP TABLE public.post;

CREATE TABLE public.post (
	id int8 NOT NULL,
	created_at date NULL,
	is_answered bool NULL,
	question varchar(100) NULL,
	response varchar(100) NULL,
	user_id int8 NULL,
	answered_at date NULL,
	CONSTRAINT post_id_not_null NOT NULL id,
	CONSTRAINT post_pkey PRIMARY KEY (id),
	CONSTRAINT fk7ky67sgi7k0ayf22652f7763r FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.question definition

-- Drop table

-- DROP TABLE public.question;

CREATE TABLE public.question (
	id int8 NOT NULL,
	answered_at date NULL,
	created_at date NULL,
	is_answered bool NULL,
	question varchar(100) NULL,
	response varchar(100) NULL,
	user_id int8 NULL,
	CONSTRAINT question_id_not_null NOT NULL id,
	CONSTRAINT question_pkey PRIMARY KEY (id),
	CONSTRAINT fk7rnpup7eaonh2ubt922ormoij FOREIGN KEY (user_id) REFERENCES public.users(id)
);